apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::704690674500:role/eksctl-simple-jwt-api1-nodegroup-NodeInstanceRole-1W1F0B3X7RLLF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<704690674500>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T19:55:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1570"
  uid: 64165651-f0b0-48a5-9780-df6dc8aafe8a
