apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::704690674500:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XMF3P19SVHM6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
        rolearn: arn:aws:iam::704690674500:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []

kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T21:57:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1327"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 91de00d6-b927-4d72-94d3-18e5d7fda2b3
